version: "2.1"

orbs:
  orb-tools: circleci/orb-tools@8.3.0
  cli: circleci/circleci-cli@0.1.3

jobs:
  validate:
    executor: cli/default
    steps:
      - checkout
      - run: circleci orb validate src/orb.yml

workflows:
  test_orb:
    jobs:
      - validate
      - orb-tools/test-in-builds:
          orb-location: src/orb.yml
          orb-name: bundle-install
          test-steps:
            - orb-tools/local-test-build:
                test-config-location: test/test.yml
